server:
  port: 8889
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    one:
      url: jdbc:mysql://localhost:3306/zhangqian?serverTimezone=UTC
      username: root
      password: 980306
      driver-class-name: com.mysql.cj.jdbc.Driver
      two:
        url: jdbc:mysql://localhost:3306/zhangqian1?serverTimezone=UTC
        username: root
        password: 980306
        driver-class-name: com.mysql.cj.jdbc.Driver
#datasource 配置链接的数据库
#logging配置日志级别
logging:
  level:
    com.wonder: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wonder.poro
